---
- name: Setup Clients
  hosts: clients
  user: ubuntu
  become: true

  vars:
    docker_enable_gvisor: true
    docker_enable_secure_bridge: true

  roles:
    - role: docker
    - role: traefik
